server:
  servlet:
    context-path: /kwx
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.183.128:33061/kwx?serverTimezone=UTC
    username: root
    password: 577308
  thymeleaf:
    encoding: utf-8
    cache: false
    prefix: classpath:/static/
    suffix: .html
mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true